spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false

ranking:
  batch:
    fixed-rate-ms: 300000
    run-slot-minutes: 5
